### PR TITLE
Feature/open rtb

### PR DESCRIPTION
**Pull request by orkhanalizada2020**

### CODE REVIEW

**Comment by eros902002** [comment]
Should we merge this to development already or maybe to an openRTB feature branch? I wouldn't merge yet since we might need to do releases before this is ready.

**Comment by orkhanalizada2020** [comment]
@eros902002 I will delete another OpenRTBAPIClient branch as it is conflicting one(after the modularization). Regarding merging, it is currently working with the Legacy API but for OpenRTB we need to wait for Remote Configs to be added to the production JSON. Maybe we could add it later on, on one of the beta releases, so we can test it

**Comment by eros902002** [comment]
Yes. With the betas we should be careful since we're releasing a lot of them and already a few publishers are asking 'cause they are confused about the versions 😄 .

**Comment by orkhanalizada2020** [comment]
@eros902002 yes, I noticed that also 😅
During holidays we got the same questions. But we also released 2 betas in a row if I'm not wrong. Maybe that's why the confusion 🤔

**Review by eros902002 — APPROVED** [review]
Looks good : )
If we merge this to development, we'd still be using the regular flow for requesting ads for now, right?

**Comment by orkhanalizada2020** [comment]
yes. As currently we do not have remote configs, it will fetch by default from the Legacy API :)

**Pull request merged**
