### PR TITLE
cleanup modules targets

### PR DESCRIPTION
**Pull request by faresbh**
- Drop support of submodules xcframework (drag and drop method)

### CODE REVIEW

**Comment by eros902002** [comment]
@faresbh does this mean that they'll be able to use the drag & drop method normally?

**Comment by faresbh** [comment]
@eros902002 Yes normal full SDK is available via drag and drop.

**Review by eros902002 — APPROVED** [review]
Looks good : )

**Comment by faresbh** [comment]
This PR will be ported to private repo. Closing here

**Pull request closed without merging**
