### PR TITLE
Remove HyBidDemo project

### PR DESCRIPTION
**Pull request by faresbh**

### CODE REVIEW

**Comment by can-soykarafakili** [comment]
This is not the private repo... I thought that we are making changes only to that repo from now on? 🤔

**Review by eros902002 — APPROVED** [review]
Looks good

**Comment by eros902002** [comment]
Ah yes. We should do it in the private repo @faresbh

**Comment by eros902002** [comment]
Once we make the next release we'll remove all branches from this repo except for master

**Pull request closed without merging**
