### PR TITLE
Development update iqv

### PR DESCRIPTION
**Pull request by faresbh**
Update IQV: 
The idea is to get rid of the special IQV branch to let them use our master branch.
Main steps:
- Merge adSizes branch.
- Merge IQV branch to development branch.
- Remove adCel API requests. 
- Maintain IQV interfaces (not used in our demo apps/Documentation)

### CODE REVIEW

**Comment by can-soykarafakili** [comment]
Our master branch does not support adSizes though. 🤔 How will that happen? Am I missing something? @faresbh @eros902002

**Comment by eros902002** [comment]
@can-soykarafakili We will release the ad sizes as well. We'll keep the old interfaces but the support for the new methods will be released. It was part of the discussion in the mobile channel.

**Comment by can-soykarafakili** [comment]
@eros902002 Right now, I do not remember 100% but the `development-genericAdSizes` branch is not keeping the old interface(s/m/l). Do we also need to add backward compatibility?

**Comment by eros902002** [comment]
@can-soykarafakili I think it is keeping the old interfaces. At least in Android we were. They were mapping to the size.

**Review by can-soykarafakili — APPROVED** [review]

**Comment by faresbh** [comment]
Regarding the adSize: I just merged adSize branch t development, not sure if you need to map old sizes. 
( Sorry for the delay) . Is it ready to merge ? @eros902002 @can-soykarafakili

**Comment by eros902002** [comment]
@faresbh the old ad sizes should be mapped already in the ad sizes branch. To check we just need to make sure that the HyBidBannerAdView, MRect and leaderboard are still there. And that the methods to auto show on load are also there and set to true, since in IQV it was set to false.

**Comment by faresbh** [comment]
@eros902002 yes, they are set to true.

**Pull request merged**
