### PR TITLE
[OMI-526] Add TCF 2.0 consent string key to user data manager

### PR DESCRIPTION
**Pull request by eros902002**
This PR contains the following changes:

- Add TCF 2.0 consent string key to UserDataManager

### CODE REVIEW

**Review by orkhanalizada2020 — APPROVED** [review]

**Comment by can-soykarafakili** [comment]
instead of master can we merge this to development? is it critical for production? @eros902002

**Comment by eros902002** [comment]
Yes. We need a hotfix release since we have publishers who want to support tcf 2.0 but can't cause we're missing a key. Chloe was asking about it today in the GDPR channel.

**Comment by eros902002** [comment]
It's making the SDK not compatible with 3rd party IAB compliant CMPs

**Comment by can-soykarafakili** [comment]
okay so if that's the case we'll release a version tomorrow. (We have to update the version in .podspec) as well @eros902002

**Comment by eros902002** [comment]
Yes. You're right @can-soykarafakili . Will add this to the PR

**Review by can-soykarafakili — APPROVED** [review]

**Pull request merged**
