### PR TITLE
Feature/connect remoteconfig auction

### PR DESCRIPTION
**Pull request by faresbh**
- Connect remote config with auctions.
- Fill VAST macros on the VAST Tag AdSource.
- Refactor auction and remote config class names with prefix HyBid.

### CODE REVIEW

**Comment by eros902002** [comment]
Shouldn't we merge this to the branch remote config branch? Just in case we don't accidentally release a config that is not ready : )

**Comment by faresbh** [comment]
@eros902002 remote config branch + auctions is already merged to development.

**Comment by eros902002** [comment]
Oh. Ok then. Let me approve it then 😄

**Review by eros902002 — APPROVED** [review]
Looks good

**Pull request merged**
